"""add user_id to trips

Revision ID: 75976035c71e
Revises: dac95293dca4
Create Date: 2026-05-10 21:46:05.237199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75976035c71e'
down_revision: Union[str, Sequence[str], None] = 'dac95293dca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DELETE FROM itineraries")
    op.execute("DELETE FROM trips")
    op.add_column('trips', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'trips', 'users', ['user_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'user_id')
    # ### end Alembic commands ###
