"""create trips table

Revision ID: a962c17ef7a2
Revises: db6d36a31e00
Create Date: 2026-05-10 19:52:19.089132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a962c17ef7a2'
down_revision: Union[str, Sequence[str], None] = 'db6d36a31e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('trip_style', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_destination'), 'trips', ['destination'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_destination'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
