"""add foreign key trip id to itineraries

Revision ID: dac95293dca4
Revises: a962c17ef7a2
Create Date: 2026-05-10 20:21:07.019861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac95293dca4'
down_revision: Union[str, Sequence[str], None] = 'a962c17ef7a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itineraries', 'trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_itineraries_trip_id'), table_name='itineraries')
    op.create_foreign_key(None, 'itineraries', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itineraries', type_='foreignkey')
    op.create_index(op.f('ix_itineraries_trip_id'), 'itineraries', ['trip_id'], unique=False)
    op.alter_column('itineraries', 'trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
